package at.ac.univie.se2.ws21.team0404.app.model.transaction;

import at.ac.univie.se2.ws21.team0404.app.model.categories.Category;

/**
 * Class, used to save information about a transaction.
 */
public class Transaction {
    private final int id;
    private final Category category;
    private final ETransactionType type;

    // id should be imo auto generated
    // TODO: change id to be autogenerated
    public Transaction(int id, Category category, ETransactionType type) {
        this.id = id;
        this.category = category;
        this.type = type;
    }

    public Category getCategory() {
        return category;
    }
    public ETransactionType getType() {
        return type;
    }

    @Override
    public int hashCode() {
        return id; // as id should be unique, it can be used as a hash code
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (!(o instanceof Transaction)) {
            return false;
        }
        Transaction that = (Transaction) o;
        return id == that.id;
    }
}
